channels:
  - bioconda
  - conda-forge
dependencies:
  - gdal=3.2.2
  - r-base=4
  - r-tidyverse
  - r-dt
  - r-ggplot2
  - r-dplyr
  - r-rlang
  - r-markdown
  - r-sf
  - r-sp
  - r-raster
  - r-terra
